# Generated by Django 4.2.11 on 2024-06-06 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneosonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='numerojugadores',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Número de Jugadores'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
