# Generated by Django 4.2.11 on 2024-06-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneosonline', '0002_torneo_creador_alter_torneo_numerojugadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='resultado',
        ),
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=24, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
